name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - run: go test

    - run: go build

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
